### ISSUE TITLE
Account footer button with Img, not svg

### ISSUE THREAD

**Issue by DenVilk** [gravity-ui/navigation#173]
How to make account button in footer of aside header like here
![image](https://github.com/gravity-ui/navigation/assets/30044072/25ab9594-1fb6-43a6-a58d-9f070c6aaa02)

When you can use only svg in items

**Comment by DarkGenius** [comment]
You can use [itemWrapper](https://github.com/gravity-ui/navigation/blob/main/src/components/types.ts#L30) to render custom icon
