### ISSUE TITLE
Popup called by More button is empty

### ISSUE THREAD

**Issue by onair-lena** [gravity-ui/navigation#278]
In AsideHeader menu items are generated mapping data array. When all items don't fit container click More button - popup is empty

https://codesandbox.io/p/sandbox/broken-flower-forked-7wqq4j?file=%2FmenuItems.tsx%3A11%2C1

**Comment by sunduckcow** [comment]
I found some type errors in your `menuItems.tsx` file:
- unnecessary nesting in each menu item (you don`t need "item" field)
- id should be a string, so i wrapped it into `String()`

fixed code looks like this: 
```ts
import { MenuItem } from "@gravity-ui/navigation";

export const menuItems: MenuItem[] = new Array(16).fill(null).map((_, ind) => ({
    id: String(ind + 1),
    title: `item ${ind + 1}`,
    icon: "",
    tooltipText: `item ${ind + 1}`,
}));
```

working version in [codesandbox](https://codesandbox.io/p/sandbox/broken-flower-forked-kqhnx4?workspaceId=b4ff44ad-7a9a-4175-8a44-7377cb5f4fae&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzcsnuo300073b6mh00i5zkz%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzcsnuo300033b6mbkim8nu7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzcsnuo300043b6mc1f05j0r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzcsnuo300063b6m37stuxha%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzcsnuo300033b6mbkim8nu7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzcsnuo300023b6megvwu63o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252FmenuItems.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzcsnuo300033b6mbkim8nu7%2522%252C%2522activeTabId%2522%253A%2522clzcsnuo300023b6megvwu63o%2522%257D%252C%2522clzcsnuo300063b6m37stuxha%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzcsnuo300053b6msu2p00c0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzcsnuo300063b6m37stuxha%2522%252C%2522activeTabId%2522%253A%2522clzcsnuo300053b6msu2p00c0%2522%257D%252C%2522clzcsnuo300043b6mc1f05j0r%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzcsnuo300043b6mc1f05j0r%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A15%257D)
